export enum DocumentType {
  CITIZENSHIP_CARD = 'CC',
  FOREIGN_ID_CARD = 'CE',
  IDENTITY_CARD = 'TI',
  PASSPORT = 'PA',
  BIRTH_CERTIFICATE = 'RC',
  DIPLOMATIC_ID = 'CD',
  SAFE_CONDUCT = 'SC',
  BIRTH_CERTIFICATE_LIVING = 'CN',
  UNIDENTIFIED_ADULT = 'AS',
  UNIDENTIFIED_MINOR = 'MS',
  TEMPORARY_PROTECTION_PERMIT = 'PT'
}
